### ISSUE TITLE
`TrieViewMut` doesn't imply `TrieView`

### ISSUE THREAD

**Issue by KrishnaSannasi** [Randevelopment/Slang#7]
This seems to be an oversight, it would be good to have a mutable view also able to act as a immutable view, so `TrieViewMut` should imply `TrieView`

**Comment by Kylebrown9** [comment]
What's the main benefit you see to returning `Result<Self, Self>` over `Option<Self>`.
I think the Result behavior is a bit non-intuitive.

**Comment by KrishnaSannasi** [comment]
If you want to easily reuse `self` if `descend` fails. It isn't necessary, but I though I would bring it up.

**Comment by Kylebrown9** [comment]
My plan for handling `descend` failures was for `descend` on `TrieView` to only borrow. So that you could simply call it again.

**Comment by KrishnaSannasi** [comment]
Ok, well due to your [review](https://github.com/Randevelopment/Slang/pull/8#discussion_r259105009) on #8, this doesn't look feasible. So I will close this issue.
